config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do
      post :make_mod
      post :ban
      resources :votes
  end

  root "home#index"

  resources :board do
      post :lock
      resources :rules
          resources :streams do
              post :sticky
              post :lock
          resources :post do
              post :ignore
              resources :votes
          end
      end
  end

  resources :announcements

  get '/board/:board_id/streams/:streams_id/post/:id/edit', to: 'post#edit'
  post '/board/:board_id/streams/:stream_id/post/:post_id/votes/create', to: 'votes#create'
  get '/board/:board_id/moderation', to: 'board#moderation'
  get '/board/:board_id/streams/:streams_id/post/:id/report', to: 'post#report'
  patch '/board/:board_id/streams/:streams_id/post/:id/report', to: 'post#report_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord

    has_many :streams, dependent: :destroy
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
    before_action :validate_admin, only: [:create, :new, :lock, :delete]
    before_action :validate_mod, only: [:moderation]

  def create
      new_board = Board.create(name: params[:name])
      redirect_to '/board/' + new_board.id.to_s + '/streams/'
  end


  def new

  end


  def index
      @boards = Board.all
      @hot_threads = []
      @boards.each do |b|
          if b.streams.sort_by{ |s| s.updated_at }.reverse.first.present?
              @hot_threads.push(b.streams.sort_by{ |s| s.updated_at }.reverse.first)
          end
      end

      @announcements = Announcement.all.reverse_order
  end

  def moderation
      if params[:page].present?
          _page = params[:page]
      else
          _page = 1
      end
      @posts = Post.where(board_id: params[:board_id], reported: true)
      @posts = @posts.paginate(page: _page, per_page: 10)
      @streams = Stream.all
      @users = User.all
      @board_name = Board.find_by_id(params[:board_id]).name
  end

  def lock
      @board = Board.find_by_id(params[:board_id])
      @lock = !@board.locked
      @board.update(locked: @lock)
      redirect_to :back
  end

  def destroy
      board = Board.find_by_id(params[:id])
      board_name = board.name
      board.destroy
      flash[:notice] = "Removed " + board_name
      redirect_to :back
  end

end

app/helpers/board_helper.rb
module BoardHelper
end

app/views/board/index.html.erb
<!-- Announcements -->
<div class="container">
    <h3><span class="glyphicon glyphicon-bullhorn"></span>Announcements</h3>
    <div class="board-announcements post-stream">
        <% @announcements.each do |announcements| %>
        <div class="col-lg-12 stream_title">
            <a href="/announcements/<%= announcements.id.to_s %>"><h4><%= announcements.title %></h4></a>
            <div>Made: <%= time_ago_in_words(announcements.created_at) %> ago</div>
        </div>
        <% end %>
    </div>
    <a href="/announcements/">View Announcements</a>
</div>

<!-- Boards -->
<div class="container">
    <h3><span class="glyphicon glyphicon-th-list"></span>Forum</h3>

    <div class="container-fluid">
        <% @boards.each do |board| %>
            <div class="col-md-4 board-title">
                <% if board.locked? %>
                    <%= link_to '<span class="board_status glyphicon glyphicon-lock"></span>'.html_safe, board_lock_path(board_id: board.id),
                        method: :post %>
                <% end %>
                <h3><a href="/board/<%= board.id %>/streams/"><%= board.name %></a></h3>
                <p>Threads: <%= board.streams.length %></p>
                <p><a href="/board/<%= board.id %>/rules/">View Rules</a></p>

                    <% if validate_mod %>
                    <div class="admin-tools">
                        <p><a href="/board/<%= board.id %>/moderation/"><span class="glyphicon glyphicon-wrench"></span>View Moderation log</a></p>
                        <% if validate_admin %>
                            <p><%= link_to '<span class="glyphicon glyphicon-wrench"></span>Delete Board'.html_safe,
                                board_path(id: board.id),
                                method: :delete,
                                data: {confirm: 'Are you sure?'} %></p>
                            <p><% if board.locked == false %>
                                <%= link_to '<span class="glyphicon glyphicon-wrench"></span>Lock Board'.html_safe, board_lock_path(board_id: board.id),
                                    method: :post %></p>
                            <% end %>
                        <% end %>
                    </div>
                    <% end %>
                </div>
        <% end %>
    </div>
</div>

<!-- Recent Threads -->
<div class="container">
    <h3><span class="glyphicon glyphicon-fire"></span>Recent Threads</h3>

    <div class="container-fluid">
        <% @hot_threads.each do |thread| %>
                <div class="col-md-4">
                    <h3><a href="/board/<%= thread.board_id %>/streams/<%= thread.id %>"><%= thread.title %></a></h3>
                    <p>Board: <%= Board.find_by_id(thread.board_id).name %> </p>
                </div>
        <% end %>
    </div>
</div>

<!-- Bottom Navigation -->
<div class="container container-fluid navbar-fixed-bottom bot-nav">
    <ul class="nav navbar-nav navbar-right">
        <% if validate_mod %>
            <li class="admin-controls admin-button"><a><span class="glyphicon glyphicon-wrench"></span></a></li>
        <% end %>
        <% if validate_admin %>
            <li><a href="/announcements/new"/>New Announcement<span class="glyphicon glyphicon-edit"></span></a></li>
            <li><a href="/board/new">New Board<span class="glyphicon glyphicon-plus"></span></a></li>
        <% end %>
    </ul>
</div>


<% if validate_admin == true %>
<script>
    lockBoard();
    deleteBoard();
</script>
<% end %>

app/views/board/moderation.html.erb
<div class="container">
    <h1> Moderation Queue for <%= @board_name %></h1>
</div>

<div class="container">
    <h1></h1>
    <div class="post-stream col-md-12">
        <% if @posts.length == 0 %>
            <h3> Moderation queue for this board is empty. </h3>
        <% else %>
            <% @posts.each do |posts| %>
                <div class="row card">

                    <div class="col-md-1">
                        <h4>
                            <a href="/users/<%= @users.find(posts.user_id).id %>"><%= @users.find(posts.user_id).name %></a>
                        </h4>
                    </div>

                    <div class="col-md-11">
                        <h4>
                            <a href="/board/<%= @streams.find(posts.stream_id).board_id.to_s%>/streams/<%= @streams.find(posts.stream_id).id.to_s%>#<%=posts.id %>">Thread: <%= @streams.find(posts.stream_id).title %></a>
                        </h4>
                        <div class="post-content col-md-9">
                            <p><%= markdown(posts.content) %></p>
                            <div class="post-footer">Posted <%= time_ago_in_words(posts.created_at) %> ago</div>
                        </div>
                        <div class="col-md-2">
                            <h4><ul>
                            <% if validate_admin %>
                                    <li><a href="/board/:/streams/:/post/<%= posts.id.to_s%>/edit"><span class="glyphicon glyphicon-edit"></span>Edit</a></li>
                            <% end %>
                                    <li>
                                    <%= link_to '<span class="glyphicon glyphicon-trash"></span>Delete'.html_safe, board_stream_post_path(stream_id: 0, id: posts.id),
                                        method: :delete,
                                        data: {confirm: 'Are you sure?'} %>
                                    </li>
                                    <%= link_to '<span class="glyphicon glyphicon-volume-off"></span>Ignore'.html_safe,
                                        board_stream_post_ignore_path(post_id: posts.id, stream_id: posts.stream_id),
                                        method: :post %>
                                    </li>
                            </ul></h4>
                        </div>

                        <div class="report-content col-md-9">
                            <p>Reason: <%= posts.rule %></p>
                        </div>


                    </div>


                </div>
            <% end %>
        <% end %>
    </div>
    <div>
        <%= will_paginate @posts, inner_window: 2, outer_window: 2 %>
        <div>
            <%= page_entries_info @posts %>
        </div>
    </div>
</div>

<div class="container container-fluid navbar-fixed-bottom bot-nav">
    <ul class="nav navbar-nav navbar-left">
        <li><a href="/board/"><span class="glyphicon glyphicon-th-list"></span> Return to Boards </a></li>
    </ul>
</div>

app/views/board/new.html.erb
<div class="container">
    <h1>Create new Board</h1>
    <%= form_tag ('/board/'), url: { action: "create", } do %>
        <div class="field">
            <%= label_tag 'Board Title: ' %></br>
            <%= text_field_tag :name, nil, required: true, size: 100, maxlength: 100 %></br>
        </div>
        <div class="action">
            <%= submit_tag 'Create Board' %>
        </div>
    <% end %>

</div>

<div class="container container-fluid navbar-fixed-bottom bot-nav">
    <ul class="nav navbar-nav navbar-left">
        <li><a href="/board/"/><span class="glyphicon glyphicon-step-backward"></span> Return to Boards</a></li>
    </ul>
</div>

app/views/board/show.html.erb
<div class="container">
    <h3><span class="glyphicon glyphicon-bullhorn"></span>Announcements</h3>
    <div class="board-announcements post-stream">
        <% @announcements.each do |announcements| %>
        <div class="card">
            <a href="/announcements/<%= announcements.id.to_s %>"><h4><%= announcements.title %></h4></a>
            <div>Made: <%= time_ago_in_words(announcements.created_at) %> ago</div>
        </div>
        <% end %>
    </div>
</div>
<div class="container">
    <h3><span class="glyphicon glyphicon-th-list"></span>Forum</h3>
    <% @boards.each do |board| %>
            <h3><a href="/board/<%= board.id %>/streams/"><%= board.name %></a></h3>
            <p>Threads: <%= board.streams.length %></p>
    <% end %>
</div>


<div class="container container-fluid navbar-fixed-bottom bot-nav">
    <ul class="nav navbar-nav navbar-right">
        <% if current_user.role == 0 %>
            <li><a href="/announcements/new"/>New Announcement<span class="glyphicon glyphicon-edit"></span></a></li>
            <li><a href="/board/new">New Board<span class="glyphicon glyphicon-plus"></span></a></li>
        <% end %>
        <li><a><span class="glyphicon"></span></a></li>
    </ul>
</div>