config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do
      post :make_mod
      post :ban
      resources :votes
  end

  root "home#index"

  resources :board do
      post :lock
      resources :rules
          resources :streams do
              post :sticky
              post :lock
          resources :post do
              post :ignore
              resources :votes
          end
      end
  end

  resources :announcements

  get '/board/:board_id/streams/:streams_id/post/:id/edit', to: 'post#edit'
  post '/board/:board_id/streams/:stream_id/post/:post_id/votes/create', to: 'votes#create'
  get '/board/:board_id/moderation', to: 'board#moderation'
  get '/board/:board_id/streams/:streams_id/post/:id/report', to: 'post#report'
  patch '/board/:board_id/streams/:streams_id/post/:id/report', to: 'post#report_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_length_of :name, maximum: 20

  has_many :streams, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :announcements, dependent: :destroy
  has_many :votes, dependent: :destroy

  def active_for_authentication?
      super && !self.banned
  end

  def inactive_message
      # Specify this case, in the event that there is
      # another issue with the account, it won't mislead them
      if self.banned
          "You've been banned."
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :validate_admin, only: [:make_mod, :ban]
    before_action :validate_user, only: [:index]

    def show
        if User.find_by_id(params[:id]).present?
            @user = User.find_by_id(params[:id])
            @posts = @user.posts.each
            @votes = Vote.where(poster_id: @user.id)
            @thumbup = @votes.where(vote: 1).sum(:vote)
            @thumbdown = @votes.where(vote: -1).sum(:vote)
            @role = get_role(@user.id)
        else
            flash[:notice] = "User not found."
            redirect_to "/users/" + current_user.id.to_s
        end
    end

    def index
        if params[:page].present?
            _page = params[:page]
        else
            _page = 1
        end

        @users = User.all
        @users = @users.paginate(page: _page, per_page: 12)
    end

    def make_mod
        user = User.find_by_id(params[:user_id])
        if user.role != 0
            if user.role == 2
                user.update(role: 1)
            else
                user.update(role: 2)
            end
            flash[:notice] = "User Moderation status changed"
            redirect_to :back
        end
    end

    def ban
        user = User.find_by_id(params[:user_id])
        unless user.role == 0
            ban_status = !user.banned
            user.update(banned: ban_status)
            flash[:notice] = "User banned status changed"
        end
        redirect_to :back
    end


    private
        #User Roles:
        #  0 => Admin
        #  1 => Mod
        #  2 => Normal User
        def get_role(uid)
            user = User.find_by_id(uid)
            role = user.role
            if user.banned
                return "Banned"
            elsif role == 0
                return "Admin"
            elsif role == 1
                return "Moderator"
            else
                return "User"
            end

        end
end

app/helpers/users_helper.rb
module UsersHelper

    def get_role(uid)
        user = User.find_by_id(uid)
        role = user.role
        if user.banned
            role_name = "Banned"
        elsif role == 0
            role_name = "Admin"
        elsif role == 1
            role_name = "Moderator"
        else
            role_name = "User"
        end

        return role_name
    end
end

app/views/users/index.html.erb
<div class="container">
    <h1> User List </h1>
</div>

<div class="container">
    <div class="container-fluid">
        <% @users.each do |user| %>
                <div class="col-md-4 board-title">
                    <h3><a href="/users/<%= user.id %>"><%= user.name %></a></h3>
                    <p><%= get_role(user.id) %></p>
                    <p>Posts: <%= user.posts.count %></p>
                </div>
        <% end %>
    </div>
    <div>
        <%= will_paginate @posts, inner_window: 2, outer_window: 2 %>
        <div>
            <%= page_entries_info @posts %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="col-md-3 username board-title">
        <h1><%= @user.name %></h1>
        <h4><%= @role %></h4>
        <h4>Posts: <%= @user.streams.count %></h4>
        <h4>Comments: <%= @user.posts.count %></h4>
        <h4> Reputation: </h4>
        <h4>
            <span class="glyphicon glyphicon-thumbs-up"></span><%= @thumbup %>
            <span class="glyphicon glyphicon-thumbs-down"></span><%= @thumbdown %>
        </h4>
        <% if validate_admin %>
            <% if @user.role == 0 %>
            <% elsif @user.role == 1 %>
                <h4>
                    <%= link_to '<span class="glyphicon glyphicon-tower"></span>Demote Moderator'.html_safe, user_make_mod_url(user_id: @user.id),
                        method: :post %>
                <h4>
            <% else %>
                <h4>
                    <%= link_to '<span class="glyphicon glyphicon-tower"></span>Make Moderator'.html_safe, user_make_mod_url(user_id: @user.id),
                        method: :post %>
                <h4>
                <% if @user.banned? %>
                    <h4>
                        <%= link_to '<span class="glyphicon glyphicon-ban-circle"></span>Remove Ban'.html_safe, user_ban_url(user_id: @user.id),
                            method: :post %>
                    <h4>
                <% else %>
                    <h4>
                        <%= link_to '<span class="glyphicon glyphicon-ban-circle"></span>Ban User'.html_safe, user_ban_url(user_id: @user.id),
                            method: :post %>
                    <h4>
                <% end %>
            <% end %>
            </h4></a>
        <% end %>
    </div>

    <!-- begin post history -->
    <div class="col-md-8 ">
        <h2> Post History</h2>
        <div class="post-history col-md-12">
            <% @posts.each do |posts| %>
                <div class="row card">
                    <div class="col-md-9">
                        <h4><a href="/board/<%= posts.board_id %>/streams/<%= posts.stream_id %>#<%=posts.id %>">
                            <%= posts.stream.title %>
                        </a></h4>
                    </div>
                    <div class="post-content col-lg-9">
                        <p><%= markdown(posts.content) %></p>
                        <div class="post-footer">Posted <%= time_ago_in_words(posts.created_at) %> ago</div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <!-- end post history -->
</div>


<% if validate_admin %>
    <script>
        addMod();
        banUser();
    </script>
<% end %>