config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do
      post :make_mod
      post :ban
      resources :votes
  end

  root "home#index"

  resources :board do
      post :lock
      resources :rules
          resources :streams do
              post :sticky
              post :lock
          resources :post do
              post :ignore
              resources :votes
          end
      end
  end

  resources :announcements

  get '/board/:board_id/streams/:streams_id/post/:id/edit', to: 'post#edit'
  post '/board/:board_id/streams/:stream_id/post/:post_id/votes/create', to: 'votes#create'
  get '/board/:board_id/moderation', to: 'board#moderation'
  get '/board/:board_id/streams/:streams_id/post/:id/report', to: 'post#report'
  patch '/board/:board_id/streams/:streams_id/post/:id/report', to: 'post#report_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stream.rb
class Stream < ApplicationRecord
    belongs_to :board
    belongs_to :user
    has_many :posts, dependent: :destroy
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_action :validate_user, only: [:create, :new]
  before_action :validate_mod, only: [:sticky, :lock, :delete]

  def create
      unless params[:title].match(" ").present?
          flash[:notice] = "Please write your titles as a sentence."
          redirect_to(:back)
      else
          if params[:title].length <= 100
              if params[:content].length <= 10000
                  content = params[:content]
                  new_stream = Stream.create(board_id: params[:board_id], user_id: current_user.id, title: params[:title])
                  current_user.posts.create(board_id: params[:board_id], stream_id: new_stream.id, content: content)

                  redirect_to board_streams_path + '/' + new_stream.id.to_s
              else
                  flash[:notice] = "Comment is too long."
                  redirect_to(:back)
              end

          else
              flash[:notice] = "Title is too long."
              redirect_to(:back)
          end
      end
  end

  def new
      @user = current_user
      @post = Post.new
      @board = Board.find_by_id(params[:board_id])
      @stream = Stream.new
  end

  def index
    if Board.find_by_id(params[:board_id]).present?
        if params[:page].present?
            _page = params[:page]
        else
            _page = 1
        end

        @streams = Stream.where(board_id: params[:board_id])
        @streams = @streams.order(is_stickied: :desc, updated_at: :desc)
        @streams = @streams.paginate(page: _page, per_page: 7)

        @board = Board.find_by_id(params[:board_id])
        @users = User.all
    else
        flash[:notice] = "Board not found."
        redirect_to "/board/"
    end
  end

  def show
      if params[:page].present?
          _page = params[:page]
      else
          _page = 1
      end

      if Stream.find_by_id(params[:id]).present?
        @posts = Post.where(stream_id: params[:id])
        @posts = @posts.paginate(page: _page, per_page: 10)
        @stream = Stream.find_by_id(params[:id])
        @board = Board.find_by_id(params[:board_id])
        @users = User.all
        @votes = Vote.all
    else
        flash[:notice] = "Thread not found."
        redirect_to "/board/"
    end
  end

  def destroy
     stream = Stream.find_by_id(params[:id])
     # Prevent Admin and Moderator streams from getting deleted
     # However, if the mod or admin posted it themselves, it can still be Removed
     # Admins can do whatever they want
     if current_user.role == 0 or User.find_by_id(stream.user_id).role > 1 or stream.user_id == current_user.id
             stream.destroy
             flash[:notice] = "Thread Removed"
             redirect_to('/board/')
     else
         flash[:notice] = "Thread couldn't be removed. Was it posted by an Admin or another Moderator?"
         redirect_to :back
     end
  end

  def sticky
      stream = Stream.find_by_id(params[:stream_id])
      sticky = !stream.is_stickied
      stream.update(is_stickied: sticky)
      redirect_to :back
  end

  def lock
      stream = Stream.find_by_id(params[:stream_id])
      lock = !stream.locked
      stream.update(locked: lock)
      redirect_to :back
  end

end

app/helpers/stream_helper.rb
module StreamHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
    def display_votes(posts)
        if user_signed_in?
            # If the current user make this post
            if current_user.posts.find_by_id(posts.id).present?
                # Don't let the users vote on their own posts
                vote_bar = '<span class="glyphicon glyphicon-thumbs-up disabled"></span>
                <span class="glyphicon glyphicon-thumbs-down disabled"></span>'
            else
                if @votes.where(post_id: posts.id, user_id: current_user.id).present?
                    # If the user has already voted
                    if @votes.where(post_id: posts.id, user_id: current_user.id).pluck(:vote) == [1]
                        # Display that they've voted up, and allow the user to vote down
                        vote_bar = '<span class="glyphicon glyphicon-thumbs-up voted"></span>
                        <span class="glyphicon glyphicon-thumbs-down vote-down" id="'+posts.id.to_s+'"></span>'
                    else
                        # Display that they've voted down, and allow the user to vote up
                        vote_bar = '<span class="glyphicon glyphicon-thumbs-up vote-up" id="'+posts.id.to_s+'"></span>
                        <span class="glyphicon glyphicon-thumbs-down voted"></span>'
                    end
                else
                    # User hasn't voted, so both buttons are enabled
                    vote_bar ='<span class="glyphicon glyphicon-thumbs-up vote-up"  id="'+posts.id.to_s+'"></span>
                    <span class="glyphicon glyphicon-thumbs-down vote-down"  id="'+posts.id.to_s+'"></span>'
                end
            end
        else
            # The user must sign in first to vote
            vote_bar ='<a href="/users/sign_in"><span class="glyphicon glyphicon-thumbs-up"></span></a>
            <a href="/users/sign_in"><span class="glyphicon glyphicon-thumbs-down"></span></a>'
        end

        return vote_bar.html_safe
    end
end

app/views/streams/index.html.erb
<div class="container">
    <h1><%= @board.name %> </h1>
</div>
<div class="container ">
    <h4><a href="/board/<%= @board.id %>/rules/">Board Rules</a></h4>
    <% unless @streams.any? %>
        <h4> No threads. :( </h4>
        <h4> Click <a href="/board/<%= @board.id %>/streams/new">here</a> to start a new one! </h4>
    <% end %>
        <div class="container-fluid">
        <% @streams.each do |streams| %>
            <div class="stream_title">
                <h3>
                    <% if streams.is_stickied? %>
                        <span class="stream_status ticky glyphicon glyphicon-paperclip"></span>
                    <% end %>
                    <% if streams.locked? %>
                        <span class="stream_status lock glyphicon glyphicon-lock"></span>
                    <% end %>
                    <a href="/board/<%= @board.id %>/streams/<%= streams.id %>"><%= streams.title %></a>
                </h3>

                <div>
                    By: <%= @users.find(streams.user_id).name %></br>
                    Posted <%= time_ago_in_words(streams.created_at) %> ago
                </div>
            </div>
        <% end %>
    </div>
    <div class="page">
        <%= will_paginate @streams, inner_window: 2, outer_window: 2 %>
        <div>
            <%= page_entries_info @posts %>
        </div>
    </div>
</div>

<nav class="container navbar-fixed-bottom bot-nav" role="navigation">
        <ul class="nav navbar-nav navbar-left hidden-sm hidden-xs">
            <li><a href="/board/"/><span class="glyphicon glyphicon-step-backward"></span> Back to Boards</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="hidden-md hidden-lg"><a href="/board/"/><span class="glyphicon glyphicon-step-backward"></span> Back to Boards</a></li>
            <li><a href="/board/<%= @board.id %>/streams/new"><span class="glyphicon glyphicon-edit"></span>New Thread</a></li>
        </ul>
</nav>

app/views/streams/new.html.erb
<div class="container">
        <h1>Make new thread  in <%= @board.name %></h1>
        <%= form_tag ('/board/' + @board.id.to_s + '/streams'), url: { action: "create", } do %>
            <div class="field">
                <%= label_tag 'Title: ' %></br>
                <%= text_field_tag :title, nil, required: true, maxlength: 100 %></br>
                <%= label_tag 'Content: '%></br>
                <%= text_area_tag :content, nil, required: true %>
            </div>
            <div class="action">
                <%= submit_tag 'Submit Post' %>
            </div>
        <% end %>
</div>

<div class="container container-fluid navbar-fixed-bottom bot-nav">
    <ul class="nav navbar-nav navbar-right">
        <li><a href="/board/"><span class="glyphicon glyphicon-step-backward"></span>Return to Boards</a></li>
    </ul>
</div>

app/views/streams/show.html.erb
<div>
    <div class="container">
        <!-- Thread Status Indicators -->
        <% if validate_mod %>
            <% if @stream.is_stickied == true %>
                <h2>
                    <%= link_to '<span class="stream_status glyphicon glyphicon-paperclip"></span>'.html_safe, board_stream_sticky_path(stream_id: @stream.id),
                        method: :post %>
                    </h2>
            <% end %>
            <% if @stream.locked == true %>
                <h2>
                    <%= link_to '<span class="stream_status glyphicon glyphicon-lock"></span>'.html_safe, board_stream_lock_path(stream_id: @stream.id),
                        method: :post %>
                    <% end %>
                </h2>
        <% else %>
            <% if @stream.is_stickied == true %>
                <h2><span class="stream_status sticky glyphicon glyphicon-paperclip" id="<%= @stream.id %>" ></span></h2>
            <% end %>
            <% if @stream.locked == true %>
                <h2><span class="stream_status lock glyphicon glyphicon-lock" id="<%= @stream.id %>" ></span></h2>
            <% end %>
        <% end %>

        <h1>
            <%= @stream.title %>
        </h1>


        <% if validate_mod %>
            <div class="admin-tools">
                <!-- Moderation Controls -->
                <a><span class="glyphicon glyphicon-trash"></span>
                <%= link_to 'Remove Thread', board_stream_path(id: @stream.id),
                    method: :delete,
                    data: {confirm: 'Are you sure?'} %>
                </a>
                <% if  @stream.is_stickied == false %>
                    <%= link_to '<span class="glyphicon glyphicon-paperclip"></span> Sticky Thread'.html_safe, board_stream_sticky_path(stream_id: @stream.id),
                        method: :post %>
                <% end %>
                <% if @stream.locked == false %>
                    <%= link_to '<span class="glyphicon glyphicon-lock"></span> Lock Thread'.html_safe, board_stream_lock_path(stream_id: @stream.id),
                        method: :post %>
                <% end %>
            </div>
        <% end %>


        <div>
            Posted by: <%= @users.find_by_id(@stream.user_id).name %>
        </div>
        <div class="post-stream col-md-12">
            <% @posts.each do |posts| %>
                <div class="row card">
                    <!-- Handling the votes on posts -->
                    <div class="col-md-1">
                        <h3>
                            <%= display_votes(posts) %>
                        </h3>

                        <p>Votes: <%= posts.votes.count %></p>
                            <h4>
                                <a href="/users/<%= User.find(posts.user_id).id %>"><%= User.find(posts.user_id).name %></a>
                            </h4>
                    </div>

                    <div class="post-content col-md-10">
                        <p><%= markdown(posts.content) %></p>
                    </div>
                    <div class="col-md-12 post-footer">
                        Posted <%= time_ago_in_words(posts.created_at) %> ago
                    </div>

                    <% if user_signed_in? %>
                        <div class="col-md-12">
                            <a href="/board/:/streams/:/post/<%= posts.id.to_s%>/report"><span class="glyphicon glyphicon-edit"></span>Report</a>
                        <% if validate_mod %>
                            <!-- Moderation Tools -->
                                <% if validate_admin %>
                                    <a href="/board/:/streams/:/post/<%= posts.id.to_s%>/edit"><span class="glyphicon glyphicon-edit"></span>Edit post</a>
                                <% end %>
                                    <%= link_to '<span class="glyphicon glyphicon-trash"></span> Delete Post'.html_safe, board_stream_post_path(stream_id: @stream.id, id: posts.id),
                                        method: :delete,
                                        data: {confirm: 'Are you sure?'} %>
                        <% end %>
                        </div>
                    <% end %>

                </div>
            <% end %>
        </div>

        <div>
            <%= will_paginate @posts, inner_window: 2, outer_window: 2 %>
            <div>
                <%= page_entries_info @posts %>
            </div>
        </div>
    </div>

    <!-- Bottom Navigation -->
    <nav class="container navbar-fixed-bottom bot-nav" role="navigation">
    		<ul class="nav navbar-nav navbar-left hidden-sm hidden-xs">
                <li><a href="/board/<%= @board.id %>/streams/"/><span class="glyphicon glyphicon-step-backward"></span> Back to <%= @board.name %></a></li>
    		</ul>
            <ul class="nav navbar-nav navbar-right">
            <% if validate_mod %>
                <li class="admin-controls admin-button"><a><span class="glyphicon glyphicon-wrench"></span></a></li>
            <% end %>

                <li class="hidden-md hidden-lg"><a href="/board/<%= @board.id %>/streams/"/><span class="glyphicon glyphicon-step-backward"></span> Back to <%= @board.name %></a></li>
                <li><a href="/board/<%= @board.id %>/streams/<%= @stream.id %>/post/new"><span class="glyphicon glyphicon-comment"></span>Reply</a></li>
            </ul>
    </nav>


</div>

<script>
    <% if user_signed_in? %>
        vote();
    <% end %>
</script>